import argparse
import json
import csv
import pathlib
import os


def main(directory):

    p_directory = pathlib.Path(directory)
    output_directory_root = p_directory / "output"

    json_file_path = output_directory_root / "s_files_generated.json"
    with open(json_file_path, "r") as f:
        s_generation_dict = json.load(f)

    # Determine complete record

    # Needed to take observation
    source_date_dict = {}




if __name__ == "__main__":
    arg_parse_obj = argparse.ArgumentParser(description="Combine fragments generated by the 'cda_to_prepared_source_fragments.py' into a single file.")
    arg_parse_obj.add_argument("-d", "--directory", dest="directory", default="./test/samples/patient_1/")
    arg_obj = arg_parse_obj.parse_args()

    main(arg_obj.directory)